---
name: CICD

on: 
  push:

jobs:
  build-and-push-builder-images:
    name: "Build and Push Images"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.8.2
          install: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: "Bake (no cache)"
        run: |
          CAN_PUSH=true TAG_FROM_GIT_REF_NAME="${{ github.ref_name }}" docker buildx bake --no-cache app
      - name: "Bake (with cache)"
        run: |
          CAN_PUSH=true TAG_FROM_GIT_REF_NAME="${{ github.ref_name }}" docker buildx bake app
      - name: "Change irrelevant file (not COPYed)"
        run: touch baz.txt
      - name: "Bake (should still have cache)"
        run: |
          CAN_PUSH=true TAG_FROM_GIT_REF_NAME="${{ github.ref_name }}" docker buildx bake app
      - name: "Change timestamp of COPYed file"
        run: touch docker-bake.hcl
      - name: "Bake (should still have cache)"
        run: |
          CAN_PUSH=true TAG_FROM_GIT_REF_NAME="${{ github.ref_name }}" docker buildx bake app
      - name: Checkout (again)
        uses: actions/checkout@v3
      - name: "Bake (should still have cache)"
        run: |
          CAN_PUSH=true TAG_FROM_GIT_REF_NAME="${{ github.ref_name }}" docker buildx bake app
  build_take_2:
    name: "Build and Push Images"
    needs: [build-and-push-builder-images]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.8.2
          install: true
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: "Bake (with cache)"
        run: |
          CAN_PUSH=true TAG_FROM_GIT_REF_NAME="${{ github.ref_name }}" docker buildx bake app
